// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0o5K-cWOzcTz6gGyYM2Tvmm2l2p8DoNM',
    appId: '1:674449130901:web:96e41a8534533a7bf3229c',
    messagingSenderId: '674449130901',
    projectId: 'udhar-6a6d3',
    authDomain: 'udhar-6a6d3.firebaseapp.com',
    storageBucket: 'udhar-6a6d3.firebasestorage.app',
    measurementId: 'G-HEJH7FR9WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6P5pm8E9t0Iqm7VFAkIF2KpkqSdT1d0',
    appId: '1:674449130901:android:417d07b790f548cdf3229c',
    messagingSenderId: '674449130901',
    projectId: 'udhar-6a6d3',
    storageBucket: 'udhar-6a6d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpicqFuJO95BVDWn4PcjpExEmw0mP-AlY',
    appId: '1:674449130901:ios:fdb5fea919df0610f3229c',
    messagingSenderId: '674449130901',
    projectId: 'udhar-6a6d3',
    storageBucket: 'udhar-6a6d3.firebasestorage.app',
    iosBundleId: 'com.example.udhar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpicqFuJO95BVDWn4PcjpExEmw0mP-AlY',
    appId: '1:674449130901:ios:fdb5fea919df0610f3229c',
    messagingSenderId: '674449130901',
    projectId: 'udhar-6a6d3',
    storageBucket: 'udhar-6a6d3.firebasestorage.app',
    iosBundleId: 'com.example.udhar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0o5K-cWOzcTz6gGyYM2Tvmm2l2p8DoNM',
    appId: '1:674449130901:web:0f30a961863925cff3229c',
    messagingSenderId: '674449130901',
    projectId: 'udhar-6a6d3',
    authDomain: 'udhar-6a6d3.firebaseapp.com',
    storageBucket: 'udhar-6a6d3.firebasestorage.app',
    measurementId: 'G-2KJF36PKCC',
  );
}
